apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service
  name: service-srm
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    nodePort: 30002
    targetPort: 3000
  selector:
    app: demo-crm
  type: NodePort
status:

